import './global/global.less'

export { default as Button } from './components/Button'
export type { ButtonProps } from './components/Button'
export { default as ConfigProvider } from './components/ConfigProvider'
export type { ConfigProviderProps } from './components/ConfigProvider'
export { default as Divider } from './components/Divider'
export type { DividerProps } from './components/Divider'
export { default as DotLoading } from './components/DotLoading'
export type { DotLoadingProps } from './components/DotLoading'
export { default as Switch } from './components/Switch'
export type { SwitchProps } from './components/Switch'
